Add /fax_lines specification and regenerate SDKs
hellosign/hellosign-openapi pull request #393
Opened 2024-08-13 19:36 UTC by jordanbardsley7

2024-08-13 20:25 UTC, maninderpalSinghHelloSign approved these changes

2024-08-22 22:47 UTC, jtreminio-dropbox requested changes

2024-08-22 22:47 UTC, jtreminio-dropbox commented on examples/FaxLineDelete.php
> +    $result = $faxLineApi->faxLineDelete($data);
`DELETE` endpoints do not return anything. Applies to other language examples.

2024-08-22 22:47 UTC, jtreminio-dropbox commented on examples/json/FaxLineAreaCodeGetResponseExample.json
> +    ]
```suggestion
    "area_codes": [
        209,
        213,
        310,
        323,
        408,
        415,
        424,
        510,
        530,
        559,
        562,
        619,
        626,
        650,
        657,
        661,
        669,
        707,
        714,
        747,
        760,
        805,
        818,
        831,
        858,
        909,
        916,
        925,
        949,
        951
    ]
```

2024-08-22 22:47 UTC, jtreminio-dropbox commented on examples/FaxLineCreate.php
> +$data->setAreaCode("209")
```suggestion
$data->setAreaCode(209)
```

Expect area code to be `int`

2024-08-26 21:02 UTC, merged